### ISSUE TITLE
C hay C++?

### ISSUE THREAD

**Issue by jimmyEllison** [Gwinnervy/luyencode.net#1]
Bạn nên thay đuôi `.cpp` sang `.c` hoặc sửa lại code. Thay vì dùng các hàm của các header ngôn ngữ C, bạn dùng các header của C++.

**Comment by sophiathedev** [comment]
Chào bạn ! Mình là bạn của chủ repo này....Mình xin góp ý thêm cho bạn là hiện tại theo như mình thấy khá ít người dùng đuôi .c (đuôi .c thì gần đây mình còn không thấy ai dùng). Còn về phần header C hay C++ thì trong code của bạn mk có thấy bạn khai báo stdio.h để dùng scanf vs printf thì mk nghĩ bạn khai báo cho chắc cú thôi chứ trong bits/stdc++.h có 2 hàm này r. Cảm ơn bạn đã góp ý !

**Comment by Gwinnervy** [comment]
Cảm ơn các bạn đã góp ý, mình sẽ tiếp thu ý kiến và cải thiện hơn
Chủ địch của cái repo này là để điều chỉnh lại kiến thức còn sai sót vì vậy các bạn cứ nhiệt tình góp ý
